FROM docker_java8dockerize

ARG PINPOINT_VERSION
ARG AGENT_ID
ARG APP_NAME
ENV APP_NAME ${APP_NAME}
ENV JAVA_OPTS="-javaagent:/pinpoint-agent/pinpoint-bootstrap-${PINPOINT_VERSION}.jar -Dpinpoint.agentId=${AGENT_ID} -Dpinpoint.applicationName=${APP_NAME}"

COPY start.sh /usr/local/bin/
RUN chmod a+x /usr/local/bin/start.sh


ADD ./jar/cloudrs-auth.jar /app/


ENTRYPOINT ["dockerize", "-timeout", "5m", "-wait", "http://cloudrs-register:9991/", "-wait", "http://cloudrs-config:8888/actuator/info","start.sh"]

