FROM chengmboy/java8-jre-enhance


ADD ./jar/cloudrs-turbine.jar /app/


ENTRYPOINT ["dockerize", "-timeout", "5m", "-wait", "http://cloudrs-register:9991/", "java", "-Xmx200m", "-jar", "/app/cloudrs-turbine.jar"]
